[package]
name = "rustowl"
version = "0.3.4"
edition = "2024"
authors = ["cordx56 <cordx56@cordx.cx>"]
description = "Visualize Ownership and Lifetimes in Rust"
documentation = "https://github.com/cordx56/rustowl/blob/main/README.md"
readme = "README.md"
repository = "https://github.com/cordx56/rustowl"
license = "MPL-2.0"
keywords = ["visualization", "ownership", "lifetime", "lsp"]
categories = ["development-tools", "visualization"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
simple_logger = { version = "5.0", features = ["stderr"] }
tokio = { version = "1.0", features = ["rt", "rt-multi-thread", "macros", "sync", "time", "io-std", "io-util", "process", "fs"] }
tower-lsp = "0.20"
process_alive = "0.1"
cargo_metadata = "0.20"
uuid = { version = "1.17", features = ["v4"] }
clap = { version = "4.5", features = ["cargo", "derive"] }
tar = "0.4"
flate2 = "1.1"
reqwest = { version = "0.12", default-features = false, features = ["http2", "rustls-tls-native-roots"] }
clap_complete_nushell = "4.5"
clap_complete = "4.5"
zip = "4.0"

[build-dependencies]
clap_complete_nushell = "4.5"
clap_complete = "4.5"
clap_mangen = "0.2"
clap = { version = "4.5", features = ["derive"] }

[dev-dependencies]
criterion = { version = "0.6", features = ["html_reports"] }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.6"
libc = "0.2"
tikv-jemalloc-sys = "0.6"

[[bench]]
name = "rustowl_bench_simple"
harness = false

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = "debuginfo"

[profile.release.package."*"]
strip = "symbols"
opt-level = 3

[profile.arm-windows-release]
inherits = "release"
lto = "off"

[profile.security]
inherits = "release"
debug = true
strip = "none"
opt-level = 3

[package.metadata.rust-analyzer]
rustc_private = true

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/rustowl-{ target }{ archive-suffix }"
pkg-fmt = "tgz"
disabled-strategies = ["quick-install", "compile"]

[package.metadata.binstall.overrides.x86_64-pc-windows-msvc]
pkg-fmt = "zip"

[package.metadata.binstall.overrides.aarch64-pc-windows-msvc]
pkg-fmt = "zip"
