[env]
MACOSX_DEPLOYMENT_TARGET = "11.0"

[target.aarch64-apple-darwin]
rustflags = [
    "-C", "link-arg=-Wl,-rpath,@loader_path",
    "-C", "link-arg=-Wl,-rpath,@loader_path/../lib", 
    "-C", "link-arg=-Wl,-rpath,@executable_path",
    "-C", "link-arg=-Wl,-rpath,@executable_path/../lib",
    "-C", "link-arg=-Wl,-rpath,/usr/local/lib",
    "-C", "link-arg=-Wl,-rpath,/usr/lib",
]
