name: Check RustOwl

on:
  workflow_call:
  pull_request:
    branches:
      - main

jobs:
  cargo:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
          - ubuntu-24.04-arm
    runs-on: ${{ matrix.os }}
    env:
      RUSTUP_TOOLCHAIN: 1.87.0
      RUSTC_BOOTSTRAP: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUSTUP_TOOLCHAIN }}
          components: clippy,rustfmt,llvm-tools,rust-src,rustc-dev
      
      - run: cargo fmt --check
      - run: cargo clippy --all-targets --all-features -- -D warnings
      
      - name: Build
        run: cargo build --release

      - name: install binaries
        run: cargo install --path .

      - name: Run RustOwl
        run: rustowl check


  vscode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: yarn install --frozen-locked
        working-directory: ./vscode
      - run: yarn prettier -c src
        working-directory: ./vscode
      - run: yarn lint && yarn check-types
        working-directory: ./vscode
