name: Setup Initial Baseline (One-time)

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTC_BOOTSTRAP: 1

jobs:
  setup-baseline:
    name: Create Initial Performance Baseline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain (from rust-toolchain.toml)
        uses: actions-rust-lang/setup-rust-toolchain@v1
        # Automatically reads nightly-2025-04-08 from rust-toolchain.toml

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install benchmark dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc gnuplot
          cargo install cargo-criterion || true

      - name: Build RustOwl
        run: |
          RUSTC_BOOTSTRAP=1 cargo build --release

      - name: Make scripts executable
        run: chmod +x scripts/*.sh

      - name: Run initial benchmark
        run: |
          echo "Creating initial performance baseline..."
          ./scripts/bench.sh --save main --quiet

      - name: Upload initial baseline
        uses: actions/upload-artifact@v4
        with:
          name: initial-performance-baseline
          path: |
            baselines/performance/main/
            target/criterion/report/
          retention-days: 90

      - name: Cache initial baseline
        uses: actions/cache/save@v3
        with:
          path: baselines/performance/main/
          key: performance-baseline-latest